tipoValor = input("Digite Algo:  ")
print("O tipo orimitivo desse valor é", type(tipoValor))
print("Só tem espaços? " ,tipoValor.isspace())
print("É um número?" ,tipoValor.isnumeric())
print("É Alfabético?" ,tipoValor.isalpha())
print("É alfanumérico?" ,tipoValor.isalnum())
print("Está em maiúscula?" ,tipoValor.isupper())
print("Está em minuscula?" ,tipoValor.islower())
print("Está capitalizada?" ,tipoValor.istitle())